### PR TITLE
Made a setup script for server

### PR DESCRIPTION
**Pull request by ReDxDaGer**

### CODE REVIEW

**Comment by kashifulhaque** [comment]
Hi, can you do a [Docker multistage build](https://docs.docker.com/build/building/multi-stage) where the download happens in one container and only the required files are copied into another Docker container.

**Comment by ReDxDaGer** [comment]
Yeah sure will do it !!

**Comment by kashifulhaque** [comment]
I have looked into the code, so far it seems very good, but ideally it should not have to depend on python. Can you isolate the python thing to docker container only. Assume that the machine where this script will be running only has docker installed.

**Comment by ReDxDaGer** [comment]
Yeah sure will do !!

**Review by kashifulhaque — APPROVED** [review]
LGTM

**Pull request merged**
